import js from "@eslint/js";
import tseslint from "typescript-eslint";
import importPlugin from "eslint-plugin-import";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/.turbo/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/*.generated.*",
      "**/generated/**",
      "packages/web/dist/**",
      // Playwright E2E specs + config live outside the src/ tsconfig include;
      // typed-lint would fail to resolve them. Kept green via `tsc --noEmit`
      // inside the playwright runner itself.
      "packages/web/e2e/**",
      "packages/web/playwright.config.ts",
      "packages/web/playwright-report/**",
      "packages/web/test-results/**",
      "website/**",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [...tseslint.configs.recommendedTypeChecked, ...tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            "vitest.workspace.ts",
            "packages/shared/vitest.config.ts",
            "packages/api/vitest.config.ts",
            "packages/db/vitest.config.ts",
            "packages/db/src/index.test.ts",
            "packages/db/src/schema.test.ts",
            "packages/test-utils/vitest.config.ts",
            "packages/worker/vitest.config.ts",
          ],
          defaultProject: "tsconfig.base.json",
        },
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },
    plugins: { import: importPlugin },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/require-await": "error",
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          // Absolute-path glob so the resolver finds per-package tsconfigs
          // regardless of whether eslint is invoked from the repo root
          // (pre-commit hook) or a package dir (`pnpm --filter <pkg> lint`).
          project: [`${import.meta.dirname}/packages/*/tsconfig.json`],
        },
      },
    },
  },
  {
    files: ["**/*.{js,mjs,cjs}"],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: { globals: { ...globals.node } },
    rules: {
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  // shadcn/ui primitives are generated by the shadcn CLI and kept close to
  // upstream so they can be upgraded by re-running `pnpm dlx shadcn add ...`.
  // Relax the house style rules for this vendor-ish directory.
  {
    files: ["packages/web/src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "import/order": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
    },
  },
  prettier,
);
