import { execFile, execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import type { FullConfig } from "@playwright/test";

const execFileP = promisify(execFile);

/**
 * Docker Compose project name for the e2e stack. Chosen so it CANNOT collide
 * with the dev stack (which uses `wpa` by default, see docker-compose.yml).
 */
export const E2E_COMPOSE_PROJECT = "wpa-e2e";

/**
 * Host port the e2e stack binds. Differs from the dev stack's 3003 so both
 * can run simultaneously on a developer's machine.
 */
export const E2E_PORT = Number(process.env.E2E_PORT ?? 3100);

/** Known admin credentials seeded by global-setup (consumed by the specs). */
export const E2E_ADMIN_EMAIL = "e2e-admin@example.com";
export const E2E_ADMIN_PASSWORD = "e2e-pass-12345678";

/** Resolve the repo root from this file's location: packages/web/e2e → ../../.. */
const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const E2E_ENV_FILE = resolve(REPO_ROOT, ".env.e2e");

function b64(size: number): string {
  return randomBytes(size).toString("base64");
}

function urlSafe(size: number): string {
  return randomBytes(size)
    .toString("base64")
    .replace(/[+/=]/g, "")
    .slice(0, size * 2);
}

/**
 * Write `.env.e2e` with the full set of keys required by @wpa/shared's
 * `parseEnv`. We do NOT touch the user's `.env` — that one belongs to the
 * dev stack.
 *
 * - MASTER_KEY: fresh per-run; e2e data is thrown away in teardown anyway.
 * - ENTRYPOINT_ROLE=api: no worker/agent. Baileys dials WhatsApp on /pair/init,
 *   which would either fail in CI (no network) or, worse, hit WA's servers with
 *   fake sessions. The pair spec simulates the worker's Redis writes directly.
 * - API_HOST_PORT=3100: host-side port. Container still listens on 3000.
 */
async function writeE2EEnv(): Promise<{ redisPassword: string }> {
  const pgPassword = urlSafe(24);
  const redisPassword = urlSafe(24);
  const content = [
    "# Generated by packages/web/e2e/global-setup.ts — do NOT commit.",
    "# Overwritten at the start of every e2e run.",
    `NODE_ENV=production`,
    `LOG_LEVEL=warn`,
    `ENTRYPOINT_ROLE=api`,
    `API_HOST_PORT=${String(E2E_PORT)}`,
    `PUBLIC_ORIGIN=http://localhost:${String(E2E_PORT)}`,
    `MASTER_KEY=${b64(32)}`,
    `JWT_SECRET=${b64(48).replace(/=/g, "")}`,
    `POSTGRES_USER=wpa`,
    `POSTGRES_DB=wpa`,
    `POSTGRES_PASSWORD=${pgPassword}`,
    `DATABASE_URL=postgresql://wpa:${pgPassword}@postgres:5432/wpa`,
    `REDIS_PASSWORD=${redisPassword}`,
    `REDIS_URL=redis://:${redisPassword}@redis:6379`,
    `OPEN_REGISTRATION=false`,
    "",
  ].join("\n");
  await writeFile(E2E_ENV_FILE, content, { mode: 0o600 });
  return { redisPassword };
}

function composeArgs(...extra: string[]): string[] {
  return [
    "compose",
    "-f",
    "docker-compose.yml",
    "-f",
    "docker-compose.e2e.yml",
    "-p",
    E2E_COMPOSE_PROJECT,
    "--env-file",
    E2E_ENV_FILE,
    ...extra,
  ];
}

async function runDocker(args: string[], opts: { timeoutMs?: number } = {}): Promise<string> {
  const { stdout } = await execFileP("docker", args, {
    cwd: REPO_ROOT,
    env: {
      ...process.env,
      COMPOSE_PROJECT_NAME: E2E_COMPOSE_PROJECT,
      API_HOST_PORT: String(E2E_PORT),
    },
    ...(opts.timeoutMs !== undefined ? { timeout: opts.timeoutMs } : {}),
    maxBuffer: 16 * 1024 * 1024,
  });
  return stdout;
}

async function waitForHealthz(timeoutMs = 180_000): Promise<void> {
  const url = `http://localhost:${String(E2E_PORT)}/healthz`;
  const deadline = Date.now() + timeoutMs;
  let lastErr: unknown = null;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
      lastErr = new Error(`status ${String(res.status)}`);
    } catch (err) {
      lastErr = err;
    }
    await new Promise((r) => setTimeout(r, 1_000));
  }
  throw new Error(
    `e2e stack failed to become healthy at ${url} within ${String(timeoutMs)}ms: ${String(lastErr)}`,
  );
}

/**
 * Seeds the admin user. First user auto-becomes admin (see
 * packages/api/src/routes/auth.ts). We treat 201 as success and 409 (already
 * exists) as OK — lets us re-run specs against an already-seeded stack during
 * local iteration.
 */
async function seedAdmin(): Promise<void> {
  const url = `http://localhost:${String(E2E_PORT)}/api/auth/register`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ email: E2E_ADMIN_EMAIL, password: E2E_ADMIN_PASSWORD }),
  });
  if (res.status === 201) return;
  // 409 on re-run is fine; anything else is a hard failure.
  if (res.status === 409) {
    // eslint-disable-next-line no-console
    console.warn("[e2e] admin already exists — reusing");
    return;
  }
  const body = await res.text().catch(() => "<no body>");
  throw new Error(`e2e admin seed failed: ${String(res.status)} ${body}. URL=${url}`);
}

/**
 * Flush Redis DB 0 so rate-limit counters from a previous local run don't
 * interfere. The compose stack uses db 0 (default). `-a` reads the password
 * from REDIS_PASSWORD in .env.e2e via env-file wiring.
 */
async function flushRedis(redisPassword: string): Promise<void> {
  // Target the redis container directly by its compose-generated name
  // (`<project>-<service>-<idx>`). The redis container doesn't receive
  // REDIS_PASSWORD as an env var (only the app service does, via env_file),
  // so we must thread the password in from the host side.
  const container = `${E2E_COMPOSE_PROJECT}-redis-1`;
  await execFileP("docker", [
    "exec",
    container,
    "redis-cli",
    "-a",
    redisPassword,
    "--no-auth-warning",
    "FLUSHDB",
  ]);
}

/**
 * Tear down any existing `wpa-e2e` stack so we start from a clean volume set.
 * Safe to call even if nothing is up — `docker compose down` succeeds silently.
 */
async function tearDownIfRunning(): Promise<void> {
  try {
    await runDocker(composeArgs("down", "-v"), { timeoutMs: 120_000 });
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn("[e2e] pre-run teardown warned:", err);
  }
}

async function bringStackUp(): Promise<void> {
  await runDocker(composeArgs("up", "-d", "--build"), { timeoutMs: 600_000 });
}

export default async function globalSetup(_config: FullConfig): Promise<void> {
  // eslint-disable-next-line no-console
  console.log(
    `[e2e] global-setup: project=${E2E_COMPOSE_PROJECT}, port=${String(E2E_PORT)}, repo=${REPO_ROOT}`,
  );

  // Sanity check: the compose file exists where we expect.
  if (!existsSync(resolve(REPO_ROOT, "docker-compose.yml"))) {
    throw new Error(`[e2e] docker-compose.yml not found at ${REPO_ROOT}`);
  }

  // Preflight: docker must be reachable. Fail fast with a helpful message.
  try {
    execFileSync("docker", ["info"], { stdio: "ignore" });
  } catch {
    throw new Error(
      "[e2e] docker daemon not reachable — start Docker before running `pnpm --filter @wpa/web test:e2e`.",
    );
  }

  const { redisPassword } = await writeE2EEnv();
  await tearDownIfRunning();
  await bringStackUp();
  await waitForHealthz();
  await flushRedis(redisPassword);
  await seedAdmin();

  // Expose for specs via env (Playwright propagates process.env to workers).
  process.env.E2E_PORT = String(E2E_PORT);
  process.env.E2E_BASE_URL = `http://localhost:${String(E2E_PORT)}`;
  process.env.E2E_ADMIN_EMAIL = E2E_ADMIN_EMAIL;
  process.env.E2E_ADMIN_PASSWORD = E2E_ADMIN_PASSWORD;
  process.env.E2E_COMPOSE_PROJECT = E2E_COMPOSE_PROJECT;

  // Persist a breadcrumb for global-teardown (Playwright doesn't share closures
  // between setup and teardown).
  const breadcrumbDir = resolve(__dirname, ".state");
  await mkdir(breadcrumbDir, { recursive: true });
  await writeFile(
    resolve(breadcrumbDir, "stack.json"),
    JSON.stringify({
      project: E2E_COMPOSE_PROJECT,
      envFile: E2E_ENV_FILE,
      port: E2E_PORT,
      repoRoot: REPO_ROOT,
    }),
    "utf8",
  );

  // eslint-disable-next-line no-console
  console.log(`[e2e] stack ready at http://localhost:${String(E2E_PORT)}`);
}
